force-app/main/default/objects/Component_Relationship__c/Component_Relationship__c.object-meta.xml
<CustomObject>
    <label>Component Relationship</label>
    <nameField>
        <label>Audio Component Relationship Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Component Relationships</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Component_Relationship__c/fields/Armboard__c.field-meta.xml
<CustomField>
    <fullName>Armboard__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Armboard</label>
    <lookupFilter>
        <active>true</active>
        <filterItems>
            <field>System_Component__c.Audio_System__c</field>
            <operation>equals</operation>
            <valueField>$Source.Audio_System__c</valueField>
        </filterItems>
        <filterItems>
            <field>System_Component__c.Audio_Component__r.RecordTypeId</field>
            <operation>equals</operation>
            <value>Armboard</value>
        </filterItems>
        <isOptional>true</isOptional>
    </lookupFilter>
    <referenceTo>System_Component__c</referenceTo>
    <relationshipLabel>Table-Tonearm Relationships</relationshipLabel>
    <relationshipName>Table_Tonearm_Relationships</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Component_Relationship__c/fields/Cartridge__c.field-meta.xml
<CustomField>
    <fullName>Cartridge__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Cartridge</label>
    <lookupFilter>
        <active>true</active>
        <filterItems>
            <field>System_Component__c.Audio_System__c</field>
            <operation>equals</operation>
            <valueField>$Source.Audio_System__c</valueField>
        </filterItems>
        <filterItems>
            <field>System_Component__c.Audio_Component__r.RecordTypeId</field>
            <operation>equals</operation>
            <value>Cartridge</value>
        </filterItems>
        <isOptional>true</isOptional>
    </lookupFilter>
    <referenceTo>System_Component__c</referenceTo>
    <relationshipLabel>Table Relationships</relationshipLabel>
    <relationshipName>Table_Relationships</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Component_Relationship__c/fields/Dest__c.field-meta.xml
<CustomField>
    <fullName>Dest__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Destination Component</label>
    <lookupFilter>
        <active>true</active>
        <filterItems>
            <field>System_Component__c.Audio_System__c</field>
            <operation>equals</operation>
            <valueField>$Source.Audio_System__c</valueField>
        </filterItems>
        <isOptional>false</isOptional>
    </lookupFilter>
    <referenceTo>System_Component__c</referenceTo>
    <relationshipLabel>Destination To</relationshipLabel>
    <relationshipName>Destination_To</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Component_Relationship__c/fields/Headshell__c.field-meta.xml
<CustomField>
    <fullName>Headshell__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Headshell</label>
    <lookupFilter>
        <active>true</active>
        <filterItems>
            <field>System_Component__c.Audio_System__c</field>
            <operation>equals</operation>
            <valueField>$Source.Audio_System__c</valueField>
        </filterItems>
        <filterItems>
            <field>System_Component__c.Audio_Component__r.RecordTypeId</field>
            <operation>equals</operation>
            <value>Headshell</value>
        </filterItems>
        <isOptional>true</isOptional>
    </lookupFilter>
    <referenceTo>System_Component__c</referenceTo>
    <relationshipLabel>Cartridge-Tonearm Relationships</relationshipLabel>
    <relationshipName>Cartridge_Tonearm_Relationships</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Component_Relationship__c/fields/Intermediate__c.field-meta.xml
<CustomField>
    <fullName>Intermediate__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Intermediate</label>
    <referenceTo>System_Component__c</referenceTo>
    <relationshipLabel>Intermediates</relationshipLabel>
    <relationshipName>Intermediates</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Component_Relationship__c/fields/Phono_Stage__c.field-meta.xml
<CustomField>
    <fullName>Phono_Stage__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Phono Stage</label>
    <lookupFilter>
        <active>true</active>
        <filterItems>
            <field>System_Component__c.Audio_System__c</field>
            <operation>equals</operation>
            <valueField>$Source.Audio_System__c</valueField>
        </filterItems>
        <filterItems>
            <field>System_Component__c.Audio_Component__r.RecordTypeId</field>
            <operation>equals</operation>
            <value>Phono Stage</value>
        </filterItems>
        <isOptional>true</isOptional>
    </lookupFilter>
    <referenceTo>System_Component__c</referenceTo>
    <relationshipLabel>Cartridge-SUT Relationships</relationshipLabel>
    <relationshipName>Cartridge_SUT_Relationships</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Component_Relationship__c/fields/Signal_Cable__c.field-meta.xml
<CustomField>
    <fullName>Signal_Cable__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Signal Cable</label>
    <lookupFilter>
        <active>true</active>
        <filterItems>
            <field>System_Component__c.Audio_System__c</field>
            <operation>equals</operation>
            <valueField>$Source.Audio_System__c</valueField>
        </filterItems>
        <filterItems>
            <field>System_Component__c.Audio_Component__r.RecordTypeId</field>
            <operation>equals</operation>
            <value>Interconnect, Speaker Cable</value>
        </filterItems>
        <isOptional>true</isOptional>
    </lookupFilter>
    <referenceTo>System_Component__c</referenceTo>
    <relationshipLabel>Signal Cables</relationshipLabel>
    <relationshipName>Signal_Cables</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Component_Relationship__c/fields/Src__c.field-meta.xml
<CustomField>
    <fullName>Src__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Source Component</label>
    <lookupFilter>
        <active>true</active>
        <filterItems>
            <field>System_Component__c.Audio_System__c</field>
            <operation>equals</operation>
            <valueField>$Source.Audio_System__c</valueField>
        </filterItems>
        <isOptional>false</isOptional>
    </lookupFilter>
    <referenceTo>System_Component__c</referenceTo>
    <relationshipLabel>Source To</relationshipLabel>
    <relationshipName>Source_To</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Component_Relationship__c/fields/SUT__c.field-meta.xml
<CustomField>
    <fullName>SUT__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>SUT</label>
    <lookupFilter>
        <active>true</active>
        <filterItems>
            <field>System_Component__c.Audio_System__c</field>
            <operation>equals</operation>
            <valueField>$Source.Audio_System__c</valueField>
        </filterItems>
        <filterItems>
            <field>System_Component__c.Audio_Component__r.RecordTypeId</field>
            <operation>equals</operation>
            <value>SUT</value>
        </filterItems>
        <isOptional>true</isOptional>
    </lookupFilter>
    <referenceTo>System_Component__c</referenceTo>
    <relationshipLabel>Cartridge-Phono Relationships</relationshipLabel>
    <relationshipName>Cartridge_Phono_Relationships</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Component_Relationship__c/fields/SUT_Cable__c.field-meta.xml
<CustomField>
    <fullName>SUT_Cable__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>SUT Cable</label>
    <lookupFilter>
        <active>true</active>
        <filterItems>
            <field>System_Component__c.Audio_System__c</field>
            <operation>equals</operation>
            <valueField>$Source.Audio_System__c</valueField>
        </filterItems>
        <filterItems>
            <field>System_Component__c.Audio_Component__r.RecordTypeId</field>
            <operation>equals</operation>
            <value>Interconnect</value>
        </filterItems>
        <isOptional>true</isOptional>
    </lookupFilter>
    <referenceTo>System_Component__c</referenceTo>
    <relationshipLabel>SUT-Phono Relationships</relationshipLabel>
    <relationshipName>SUT_Phono_Relationships</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Component_Relationship__c/fields/Table__c.field-meta.xml
<CustomField>
    <fullName>Table__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Table</label>
    <lookupFilter>
        <active>true</active>
        <filterItems>
            <field>System_Component__c.Audio_System__c</field>
            <operation>equals</operation>
            <valueField>$Source.Audio_System__c</valueField>
        </filterItems>
        <filterItems>
            <field>System_Component__c.Audio_Component__r.RecordTypeId</field>
            <operation>equals</operation>
            <value>Turntable</value>
        </filterItems>
        <isOptional>true</isOptional>
    </lookupFilter>
    <referenceTo>System_Component__c</referenceTo>
    <relationshipLabel>Cartridge Relationships</relationshipLabel>
    <relationshipName>Cartridge_Relationships</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Component_Relationship__c/fields/Table_Cartridge__c.field-meta.xml
<CustomField>
    <fullName>Table_Cartridge__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Table-Cartridge</label>
    <lookupFilter>
        <active>true</active>
        <filterItems>
            <field>Component_Relationship__c.Audio_System__c</field>
            <operation>equals</operation>
            <valueField>$Source.Audio_System__c</valueField>
        </filterItems>
        <isOptional>true</isOptional>
    </lookupFilter>
    <referenceTo>Component_Relationship__c</referenceTo>
    <relationshipLabel>Cartridge-Phono Relationships</relationshipLabel>
    <relationshipName>Cartridge_Phono_Relationships</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Component_Relationship__c/fields/Tonearm__c.field-meta.xml
<CustomField>
    <fullName>Tonearm__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Tonearm</label>
    <lookupFilter>
        <active>true</active>
        <filterItems>
            <field>System_Component__c.Audio_System__c</field>
            <operation>equals</operation>
            <valueField>$Source.Audio_System__c</valueField>
        </filterItems>
        <filterItems>
            <field>System_Component__c.Audio_Component__r.RecordTypeId</field>
            <operation>equals</operation>
            <value>Tonearm</value>
        </filterItems>
        <isOptional>true</isOptional>
    </lookupFilter>
    <referenceTo>System_Component__c</referenceTo>
    <relationshipLabel>Table-Cartridge Relationships</relationshipLabel>
    <relationshipName>Table_Cartridge_Relationships</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Component_Relationship__c/fields/Tonearm_Cable__c.field-meta.xml
<CustomField>
    <fullName>Tonearm_Cable__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Tonearm Cable</label>
    <lookupFilter>
        <active>true</active>
        <filterItems>
            <field>System_Component__c.Audio_System__c</field>
            <operation>equals</operation>
            <valueField>$Source.Audio_System__c</valueField>
        </filterItems>
        <filterItems>
            <field>System_Component__c.Audio_Component__r.RecordTypeId</field>
            <operation>equals</operation>
            <value>Interconnect</value>
        </filterItems>
        <isOptional>true</isOptional>
    </lookupFilter>
    <referenceTo>System_Component__c</referenceTo>
    <relationshipLabel>Tonearm-Cable Relationships</relationshipLabel>
    <relationshipName>Tonearm_Cable_Relationships</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Component_Relationship__c/fields/Tube__c.field-meta.xml
<CustomField>
    <fullName>Tube__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Tube</label>
    <lookupFilter>
        <active>true</active>
        <filterItems>
            <field>System_Component__c.Audio_System__c</field>
            <operation>equals</operation>
            <valueField>$Source.Audio_System__c</valueField>
        </filterItems>
        <filterItems>
            <field>System_Component__c.Audio_Component__r.RecordTypeId</field>
            <operation>equals</operation>
            <value>Tube</value>
        </filterItems>
        <isOptional>true</isOptional>
    </lookupFilter>
    <referenceTo>System_Component__c</referenceTo>
    <relationshipLabel>Tubed Component Relationships</relationshipLabel>
    <relationshipName>Tubed_Component_Relationships</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Component_Relationship__c/fields/Tubed_Component__c.field-meta.xml
<CustomField>
    <fullName>Tubed_Component__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Tubed Component</label>
    <lookupFilter>
        <active>true</active>
        <filterItems>
            <field>System_Component__c.Audio_System__c</field>
            <operation>equals</operation>
            <valueField>$Source.Audio_System__c</valueField>
        </filterItems>
        <filterItems>
            <field>System_Component__c.Audio_Component__r.RecordTypeId</field>
            <operation>equals</operation>
            <value>Preamplifier, Amplifier, Phono Stage</value>
        </filterItems>
        <isOptional>true</isOptional>
    </lookupFilter>
    <referenceTo>System_Component__c</referenceTo>
    <relationshipLabel>Tube Relationships</relationshipLabel>
    <relationshipName>Tube_Relationships</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Component_Relationship__c/recordTypes/Accessory_Component.recordType-meta.xml
<RecordType>
    <fullName>Accessory_Component</fullName>
    <active>true</active>
    <label>Accessory-Component</label>
</RecordType>

force-app/main/default/objects/Component_Relationship__c/recordTypes/Amp_Speaker.recordType-meta.xml
<RecordType>
    <fullName>Amp_Speaker</fullName>
    <active>true</active>
    <label>Amp-Speaker</label>
</RecordType>

force-app/main/default/objects/Component_Relationship__c/recordTypes/Cartridge_Phono.recordType-meta.xml
<RecordType>
    <fullName>Cartridge_Phono</fullName>
    <active>true</active>
    <label>Cartridge-Phono</label>
</RecordType>

force-app/main/default/objects/Component_Relationship__c/recordTypes/Component_Component.recordType-meta.xml
<RecordType>
    <fullName>Component_Component</fullName>
    <active>true</active>
    <label>Component-Component</label>
</RecordType>

force-app/main/default/objects/Component_Relationship__c/recordTypes/Table_Cartridge.recordType-meta.xml
<RecordType>
    <fullName>Table_Cartridge</fullName>
    <active>true</active>
    <label>Table-Cartridge</label>
</RecordType>

force-app/main/default/objects/Component_Relationship__c/recordTypes/Tube_Component.recordType-meta.xml
<RecordType>
    <fullName>Tube_Component</fullName>
    <active>true</active>
    <label>Tube-Component</label>
</RecordType>

force-app/main/default/classes/ComponentRelationshipTriggerHandler.cls
public class ComponentRelationshipTriggerHandler {

    public static void handle() {
        Map<Id, RecordTypeInfo> typeMap = Schema.Component_Relationship__c.sObjectType.getDescribe().getRecordTypeInfosById();
        Set<Id> compScope = new Set<Id>();
        Set<Id> compRelScope = new Set<Id>();
        for (Component_Relationship__c rel : (Component_Relationship__c []) Trigger.new) {
            RecordTypeInfo typeInfo = typeMap.get(rel.RecordTypeId);
            String typeName = typeInfo.getDeveloperName();
            if (typeName == 'Tube_Component') {
                rel.Src__c = rel.Tube__c;
                rel.Dest__c = rel.Tubed_Component__c;
                compScope.add(rel.Tube__c);
                compScope.add(rel.Tubed_Component__c);
            } else if (typeName == 'Cartridge_Phono') {
                compRelScope.add(rel.Table_Cartridge__c);
                rel.Dest__c = rel.Phono_Stage__c;
                rel.Intermediate__c = rel.SUT__c;
                rel.Signal_Cable__c = rel.SUT_Cable__c;
                compScope.add(rel.Phono_Stage__c);
                compScope.add(rel.SUT__c);
                compScope.add(rel.SUT_Cable__c);
            } else if (typeName == 'Table_Cartridge') {
                rel.Src__c = rel.Table__c;
                rel.Dest__c = rel.Cartridge__c;
                rel.Intermediate__c = rel.Tonearm__c;
                rel.Signal_Cable__c = rel.Tonearm_Cable__c;
                compScope.add(rel.Table__c);
                compScope.add(rel.Cartridge__c);
                compScope.add(rel.Tonearm__c);
                compScope.add(rel.Armboard__c);
                compScope.add(rel.Tonearm_Cable__c);
                compScope.add(rel.Headshell__c);
                compScope.add(rel.Headshell_Leads__c);
            } else if (typeName == 'Component_Component') {
                rel.Src__c = rel.Upstream__c;
                rel.Dest__c = rel.Downstream__c;
                rel.Signal_Cable__c = rel.Interconnect__c;
                rel.Intermediate__c = rel.Interconnect__c;
                compScope.add(rel.Upstream__c);
                compScope.add(rel.Downstream__c);
                compScope.add(rel.Interconnect__c);
            } else if (typeName == 'Accessory_Component') {
                rel.Src__c = rel.Accessory__c;
                rel.Dest__c = rel.Accessorized_Component__c;
                compScope.add(rel.Accessory__c);
                compScope.add(rel.Accessorized_Component__c);
            } else if (typeName == 'Amp_Speaker') {
                rel.Src__c = rel.Amp__c;
                rel.Dest__c = rel.Speakers__c;
                compScope.add(rel.Amp__c);
                compScope.add(rel.Speakers__c);
                Id[] cables = new Id[]{ rel.Full_Range_Cable__c, rel.Treble_Cable__c, rel.Bass_Cable__c };
                compScope.addAll(cables);
                for (Id c : cables) {
                    if (c != null) {
                        rel.Intermediate__c = c;
                        rel.Signal_Cable__c = c;
                        break;
                    }
                }
            }
        }
        Map<Id, Component_Relationship__c> compRelMap = new Map<Id, Component_Relationship__c>([ 
            SELECT Name, Table__c, Table_Cartridge__r.Cartridge__c, Cartridge__c, Tonearm__c, Tonearm_Cable__c, Armboard__c, Headshell__c, Headshell_Leads__c
            FROM Component_Relationship__c
            WHERE Id IN :(compRelScope) ]);
        
        for (Component_Relationship__c compRel : (Component_Relationship__c []) compRelMap.values()) {
            compScope.addAll(new Id[]{ compRel.Table__c, compRel.Cartridge__c, compRel.Tonearm__c, compRel.Tonearm_Cable__c, 
                compRel.Armboard__c, compRel.Headshell__c, compRel.Headshell_Leads__c });
            if (compRel.Table_Cartridge__r != null) {
                compScope.add(compRel.Table_Cartridge__r.Cartridge__c);
            }
        }
        compScope.remove(null);
        Map<Id, Audio_Component__c> compMap = new Map<Id, Audio_Component__c>();
        for (System_Component__c sc : [ 
                SELECT Audio_Component__r.Model__c, Audio_Component__r.Manufacturer__c 
                FROM System_Component__c 
                WHERE Id IN :(compScope) ]) {
            compMap.put(sc.Id, sc.Audio_Component__r);
        }
        
        for (Component_Relationship__c rel : (Component_Relationship__c []) Trigger.new) {
            RecordTypeInfo typeInfo = typeMap.get(rel.RecordTypeId);
            String typeName = typeInfo.getDeveloperName();
            String[] nameParts;
            switch on typeName {
                when 'Tube_Component' {
                    // "[RCA 12AX7] In [VAC Renaissance SE]"
                    //nameParts = new String(){ rel. }
                    Audio_Component__c tube = compMap.get(rel.Tube__c);
                    Audio_Component__c tubedComp = compMap.get(rel.Tubed_Component__c);
                    System.debug(rel);
                    System.debug(compMap);
                    System.debug(tube);
                    rel.Name = substr(String.format('[{0}] In [{1}]', new String[]{
                        String.join(new String[]{ tube.Manufacturer__c, tube.Model__c }, ' '), 
                        String.join(new String[]{ tubedComp.Manufacturer__c, tubedComp.Model__c }, ' ')
                    }), 80);
                }
                when 'Amp_Speaker' {
                    // "[Phison A2.120 SE] Drives [Tannoy Canterbury GR] Full-Range"
                    Audio_Component__c amp = compMap.get(rel.Amp__c);
                    Audio_Component__c speak = compMap.get(rel.Speakers__c);
                    rel.Name = substr(String.format('[{0}] Drives [{1}] {2}', new String[]{
                        String.join(new String[]{ amp.Manufacturer__c, amp.Model__c }, ' '), 
                        String.join(new String[]{ speak.Manufacturer__c, speak .Model__c }, ' '),
                        rel.Amp_Configuration__c
                    }), 80);
                }
                when 'Table_Cartridge' {
                    // "[Koetsu Blue Lace] On [FR64S] / [Master Innovation]"
                    Audio_Component__c cart = compMap.get(rel.Cartridge__c);
                    Audio_Component__c arm = compMap.get(rel.Tonearm__c);
                    Audio_Component__c table = compMap.get(rel.Table__c);
                    rel.Name = substr(String.format('[{0}] On [{1}] / [{2}]', new String[]{
                        String.join(new String[]{ cart.Manufacturer__c, cart.Model__c }, ' '), 
                        arm.Model__c,
                        table.Model__c
                    }), 80);
                }
                when 'Cartridge_Phono' {
                    // "[Koetsu Blue Lace] / [FR64S] Into [EAR MC-3] And [Reference 3SE]"
                    Id cartSysCompId = compRelMap.get(rel.Table_Cartridge__c)?.Cartridge__c;
                    Audio_Component__c arm = compMap.get(compRelMap.get(rel.Table_Cartridge__c).Tonearm__c);
                    Audio_Component__c cart = compMap.get(cartSysCompId); //compMap.get(rel.Cartridge__c);
                    Audio_Component__c sut = compMap.get(rel.SUT__c);
                    Audio_Component__c phono = compMap.get(rel.Phono_Stage__c);
                    rel.Src__c = cartSysCompId;
                    if (sut != null) { 
                        rel.Name = substr(String.format('[{0}] / [{1}] Into [{2}] And [{3}]', new String[]{
                            String.join(new String[]{ cart?.Manufacturer__c, cart?.Model__c }, ' '), 
                            arm.Model__c,
                            String.join(new String[]{ sut?.Manufacturer__c, sut?.Model__c }, ' '),
                            phono.Model__c
                        }), 80);
                    } else { 
                        rel.Name = substr(String.format('[{0}] / [{1}] Into [{2}]', new String[]{
                            String.join(new String[]{ cart?.Manufacturer__c, cart?.Model__c }, ' '), 
                            arm.Model__c,
                            phono.Model__c
                        }), 80);
                    }
                }
                when 'Component_Component' {
                    // "[Koetsu Blue Lace] On [FR64S] / [Master Innovation]"
                    Audio_Component__c upstream = compMap.get(rel.Upstream__c);
                    Audio_Component__c downstream = compMap.get(rel.Downstream__c);
                    rel.Name = substr(String.format('[{0}] Into [{1}]', new String[]{
                        String.join(new String[]{ upstream.Manufacturer__c, upstream.Model__c }, ' '), 
                        String.join(new String[]{ downstream.Manufacturer__c, downstream.Model__c }, ' ')
                    }), 80);
                }
                when 'Accessory_Component' {
                    // "[Koetsu Blue Lace] On [FR64S] / [Master Innovation]"
                    Audio_Component__c accessory = compMap.get(rel.Accessory__c);
                    Audio_Component__c accesorized = compMap.get(rel.Accessorized_Component__c);
                    rel.Name = substr(String.format('[{0}] For [{1}]', new String[]{
                        String.join(new String[]{ accessory .Manufacturer__c, accessory.Model__c }, ' '), 
                        String.join(new String[]{ accesorized .Manufacturer__c, accesorized .Model__c }, ' ')
                    }), 80);
                }
            }
        }
    }

    static String substr(String val, Integer len) {
        return val != null && val.length() > 80 ? val.substring(0, len) : val;
    }
}